const D=window.ICEC_DATA;
const KEYS={recipes:'icec_user_recipes_v2',ingredients:'icec_ingredients_v2',profiles:'icec_profiles_v2',recipeMeta:'icec_recipe_meta_v2',productions:'icec_productions_v3'};
const DEFAULT_PROFILES={
 cream:{label:'Creme / base latte',ranges:{sugars:[18,22],fat:[7,16],msnf:[7,12],solids:[37,46],pac:[22,28],pod:[16,22]}},
 choc:{label:'Cioccolato',ranges:{sugars:[18,23],fat:[6,14],msnf:[5,11],solids:[38,48],pac:[22,29],pod:[16,23]}},
 nuts:{label:'Frutta secca',ranges:{sugars:[17,22],fat:[8,16],msnf:[5,11],solids:[38,48],pac:[22,29],pod:[15,22]}},
 fruit:{label:'Frutta',ranges:{sugars:[22,24],fat:[0,10],msnf:[0,7],solids:[32,42],pac:[26,34],pod:[20,26]}},
 sorbet:{label:'Sorbetto',ranges:{sugars:[22,28],fat:[0,3],msnf:[0,2],solids:[30,40],pac:[27,35],pod:[21,28]}},
 granita:{label:'Granita',ranges:{sugars:[14,24],fat:[0,3],msnf:[0,2],solids:[14,30],pac:[18,32],pod:[14,25]}}
};
const clone=o=>JSON.parse(JSON.stringify(o)), $=s=>document.querySelector(s), fmt=(n,d=1)=>Number(n||0).toLocaleString('it-IT',{minimumFractionDigits:d,maximumFractionDigits:d});
const getJSON=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}, setJSON=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
let profiles=getJSON(KEYS.profiles,clone(DEFAULT_PROFILES)); let draftProfiles=clone(profiles);
let ingredientDB=getJSON(KEYS.ingredients,null)||D.ingredients.map(i=>({...i,_legacy:true}));
let state={items:[],advanced:false,profile:'cream',service:'display',temp:-13,notes:'',loadedId:null,loadedName:'Nuova ricetta'};
function userRecipes(){return getJSON(KEYS.recipes,[])} function recipeMeta(){return getJSON(KEYS.recipeMeta,{})}
function allRecipes(){let meta=recipeMeta();return [...D.recipes.filter(r=>!meta[r.id]?.deleted).map(r=>({...r,name:meta[r.id]?.name||r.name,category:meta[r.id]?.category||'unclassified',notes:meta[r.id]?.notes||r.notes||''})),...userRecipes()]}
function ing(id){return ingredientDB.find(x=>x.id===id)}
function missingFields(i){if(!i)return ['ingrediente'];let miss=[]; if(i.cost==null||(i._legacy&&i.cost===0&&!/^(acqua|sale)$/i.test(i.name)))miss.push('costo'); ['kcal','carbs','sugars','fat','protein','solids','water','pac','pod'].forEach(k=>{if(i[k]==null)miss.push(k)}); if(i._legacy&&Object.values(i).filter(v=>v===0).length>=8&&!/^acqua$/i.test(i.name))miss.push('dati tecnici da verificare'); return [...new Set(miss)]}
function calc(){let total=state.items.reduce((a,x)=>a+(+x.grams||0),0),m={kcal:0,carbs:0,sugars:0,fat:0,protein:0,fiber:0,salt:0,msnf:0,solids:0,water:0,pac:0,pod:0,cost:0};state.items.forEach(x=>{let i=ing(x.ingredientId);if(!i)return;Object.keys(m).forEach(k=>{let v=i[k];if(v==null)return;if(k==='cost')m[k]+=x.grams*v/1000;else m[k]+=x.grams*v/100})});if(total){['carbs','sugars','fat','protein','fiber','salt','msnf','solids','water','pac','pod'].forEach(k=>m[k]=m[k]/total*100);m.kcal=m.kcal/total*100}return{total,m}}
function serviceRange(key,base){if(key!=='pac')return base;if(state.service==='home')return[Math.max(base[0],27),Math.max(base[1],34)];if(state.service==='custom'){let shift=Math.max(0,(-state.temp-13)*.9);return[base[0]+shift,base[1]+shift]}return base}
function status(v,r){if(v>=r[0]&&v<=r[1])return'good';let dist=v<r[0]?(r[0]-v)/(r[1]||1):(v-r[1])/(r[1]||1);return dist<.12?'warn':'bad'}
function profileOptions(selected,allowUn=true){return (allowUn?'<option value="unclassified">Non classificata</option>':'')+Object.entries(profiles).map(([k,p])=>`<option value="${k}" ${k===selected?'selected':''}>${p.label}</option>`).join('')}
function renderFormula(){let{total}=calc();$('#formula').innerHTML=state.items.length?state.items.map((x,n)=>`<div class="frow ${x.ingredientId&&missingFields(ing(x.ingredientId)).length?'hasMissing':''}"><select onchange="setIng(${n},this.value)"><option value="">Seleziona ingrediente…</option>${ingredientDB.map(i=>`<option value="${i.id}" ${i.id===x.ingredientId?'selected':''}>${i.name}</option>`).join('')}</select><input type="number" step="0.1" value="${x.grams||''}" placeholder="g" onchange="setG(${n},this.value)"><div class="pct">${total?fmt(x.grams/total*100):0}%</div><button class="del" onclick="delRow(${n})">×</button></div>`).join(''):'<div class="empty">Aggiungi il primo ingrediente per iniziare.</div>';$('#totalG').textContent=fmt(total,1)+' g';$('#totalTarget').value=Math.round(total);renderMetrics()}
window.setIng=(n,v)=>{state.items[n].ingredientId=v;renderFormula()};window.setG=(n,v)=>{state.items[n].grams=Math.max(0,+v||0);renderFormula()};window.delRow=n=>{state.items.splice(n,1);renderFormula()};
function quality(){let issues=[];state.items.forEach(x=>{if(!x.ingredientId)return issues.push('Una riga non ha ancora un ingrediente selezionato.');let i=ing(x.ingredientId),m=missingFields(i);if(m.length)issues.push(`${i.name}: ${m.join(', ')}`)});return issues}
function renderMetrics(){let{total,m}=calc(),p=profiles[state.profile]||profiles.cream,keys=state.advanced?['sugars','fat','protein','msnf','solids','water','pac','pod','kcal','carbs','fiber','salt']:['sugars','fat','protein','solids','water','pac','pod','kcal'];let labels={sugars:'Zuccheri',fat:'Grassi',protein:'Proteine',msnf:'MSNF',solids:'Solidi totali',water:'Acqua',pac:'PAC',pod:'POD',kcal:'kcal / 100g',carbs:'Carboidrati',fiber:'Fibre',salt:'Sale'},scored=[];$('#metrics').innerHTML=keys.map(k=>{let r=p.ranges[k]?serviceRange(k,p.ranges[k]):null,s=r?status(m[k],r):'';if(r)scored.push(s);let unit=['pac','pod','kcal'].includes(k)?'':'%';return`<div class="metric ${s}"><small>${labels[k]}</small><b>${fmt(m[k],k==='salt'?2:1)}${unit}</b>${r?`<em>target ${fmt(r[0],0)}–${fmt(r[1],0)}</em>`:''}</div>`}).join('');let good=scored.filter(x=>x==='good').length,score=scored.length?Math.round(good/scored.length*100):0;$('#ring').textContent=score;$('#scoreText').textContent=!total?'In attesa':score>=85?'Ben bilanciata':score>=60?'Da rifinire':'Da ribilanciare';$('#scoreDetail').textContent=total?`${good}/${scored.length} parametri nel range · ${p.label}`:'Aggiungi ingredienti alla formula.';let issues=quality();$('#qualityAlert').innerHTML=issues.length?`<div class="quality"><b>Completezza dati: attenzione</b><span>${issues.length} segnalazion${issues.length===1?'e':'i'}. Alcuni risultati possono essere incompleti.</span><button onclick="showQuality()">Dettagli</button></div>`:'';let adv=[];for(const k of Object.keys(p.ranges)){let r=serviceRange(k,p.ranges[k]),v=m[k];if(v<r[0])adv.push(`${labels[k]} basso (${fmt(v)}): target ${fmt(r[0],0)}–${fmt(r[1],0)}.`);if(v>r[1])adv.push(`${labels[k]} alto (${fmt(v)}): target ${fmt(r[0],0)}–${fmt(r[1],0)}.`)}if(state.service==='home')adv.unshift('Valutazione per freezer domestico: il PAC viene contestualizzato alla temperatura più bassa. Verifica la consistenza reale dopo 12–24 h.');$('#advice').innerHTML=total?(adv.length?adv.slice(0,5).map(x=>'• '+x).join('<br>'):'Parametri principali nel range. Registra comunque la prova sensoriale.'):'Il motore di bilanciamento si attiverà con la formula.';let missingCost=state.items.some(x=>x.ingredientId&&missingFields(ing(x.ingredientId)).includes('costo'));$('#costTotal').textContent=(missingCost?'≥ ':'')+'€ '+fmt(m.cost,2)+(missingCost?' · incompleto':'');$('#costKg').textContent=(missingCost?'≥ ':'')+'€ '+fmt(total?m.cost/total*1000:0,2)+(missingCost?' · incompleto':'')}
window.showQuality=()=>openModal(`<h2>Completezza della ricetta</h2><p>Un valore mancante non viene trattato come zero.</p><div class="issueList">${quality().map(x=>`<div>⚠ ${x}</div>`).join('')}</div>`);
function newRecipe(){state={...state,items:[],profile:'cream',notes:'',loadedId:null,loadedName:'Nuova ricetta'};$('#recipeLoad').value='';$('#profile').value=state.profile;$('#notes').value='';$('#loadedName').textContent=state.loadedName;renderFormula();renderProductionHistory()}
function loadRecipe(id){let r=allRecipes().find(x=>x.id===id);if(!r)return;state.items=r.items.filter(x=>x.ingredientId).map(x=>({...x}));state.notes=r.notes||'';state.loadedId=id;state.loadedName=r.name;state.profile=r.category&&r.category!=='unclassified'?r.category:'cream';$('#profile').value=state.profile;$('#notes').value='';$('#loadedName').textContent=r.name;renderFormula();renderProductionHistory()}
function fillRecipeSelect(){let rs=allRecipes();$('#recipeLoad').innerHTML='<option value="">— Carica una ricetta —</option>'+rs.map(r=>`<option value="${r.id}">${r.name}</option>`).join('');$('#dbcount').textContent=`${ingredientDB.length} ingredienti · ${rs.length} ricette`;$('#profile').innerHTML=profileOptions(state.profile,false)}
function completeness(i){let m=missingFields(i);return m.length?`<span class="badge warnBadge">${m.length} da verificare</span>`:''}
function renderIngredients(q=''){let rows=ingredientDB.filter(i=>i.name.toLowerCase().includes(q.toLowerCase()));$('#ingredientList').innerHTML=rows.map(i=>`<button class="ingredientRow" onclick="editIngredient('${i.id}')"><div><b>${i.name}</b><small>${i.category||'Categoria non impostata'}</small></div><div class="miniStats"><span>Zuccheri <b>${i.sugars==null?'—':fmt(i.sugars)}%</b></span><span>Grassi <b>${i.fat==null?'—':fmt(i.fat)}%</b></span><span>PAC <b>${i.pac==null?'—':fmt(i.pac)}</b></span><span>POD <b>${i.pod==null?'—':fmt(i.pod)}</b></span><span>€/kg <b>${i.cost==null?'—':fmt(i.cost,2)}</b></span></div>${completeness(i)}<span class="chev">›</span></button>`).join('')||'<div class="empty">Nessun ingrediente trovato.</div>'}
window.editIngredient=id=>ingredientModal(ing(id));
function ingredientModal(i=null){let fields=[['kcal','kcal'],['carbs','Carboidrati %'],['sugars','Zuccheri %'],['fat','Grassi %'],['protein','Proteine %'],['fiber','Fibre %'],['salt','Sale %'],['msnf','MSNF %'],['solids','Solidi %'],['water','Acqua %'],['pac','PAC'],['pod','POD'],['cost','Costo €/kg']],miss=i?missingFields(i):[];openModal(`<h2>${i?'Modifica ingrediente':'Nuovo ingrediente'}</h2>${miss.length?`<div class="quality"><b>Dati da completare</b><span>${miss.join(', ')}</span></div>`:''}<form id="ingForm"><label>Nome<input name="name" required value="${i?.name||''}"></label><label>Categoria<input name="category" value="${i?.category||''}" placeholder="Es. Latte, Zucchero, Frutta secca"></label><div class="formGrid">${fields.map(([k,l])=>`<label class="${miss.includes(k)?'missingField':''}">${l}<input name="${k}" type="number" step="0.01" value="${i?.[k]??''}" placeholder="Dato non disponibile"></label>`).join('')}</div><div class="modalActions">${i?'<button type="button" class="danger" id="deleteIng">Elimina</button><button type="button" id="duplicateIng">Duplica</button>':''}<button class="primary" type="submit">Salva ingrediente</button></div></form>`);$('#ingForm').onsubmit=e=>{e.preventDefault();let fd=new FormData(e.target),obj={id:i?.id||'ui'+Date.now(),_legacy:false};for(let[k,v]of fd.entries())obj[k]=k==='name'||k==='category'?v.trim():(v===''?null:+v);let ix=ingredientDB.findIndex(x=>x.id===obj.id);if(ix>=0)ingredientDB[ix]=obj;else ingredientDB.push(obj);setJSON(KEYS.ingredients,ingredientDB);closeModal();renderIngredients($('#ingSearch').value);renderFormula();fillRecipeSelect()};if(i){$('#duplicateIng').onclick=()=>{closeModal();ingredientModal({...i,id:null,name:i.name+' copia',_legacy:false})};$('#deleteIng').onclick=()=>{let used=allRecipes().filter(r=>r.items.some(x=>x.ingredientId===i.id));if(used.length){alert(`Ingrediente usato in ${used.length} ricett${used.length===1?'a':'e'}. Rimuovilo prima dalle ricette.`);return}if(!confirm(`Eliminare definitivamente "${i.name}"?`))return;ingredientDB=ingredientDB.filter(x=>x.id!==i.id);setJSON(KEYS.ingredients,ingredientDB);closeModal();renderIngredients($('#ingSearch').value);fillRecipeSelect()}}}
let recipeFilter='all',recipeQuery='';
function renderRecipes(filter=recipeFilter){recipeFilter=filter;let rs=allRecipes(),cats={unclassified:'Non classificata',...Object.fromEntries(Object.entries(profiles).map(([k,v])=>[k,v.label]))};$('#recipeFilters').innerHTML=['all',...Object.keys(cats)].map(k=>`<button class="chip ${k===recipeFilter?'active':''}" onclick="renderRecipes('${k}')">${k==='all'?'Tutte':cats[k]}</button>`).join('');let shown=recipeFilter==='all'?rs:rs.filter(r=>r.category===recipeFilter);shown=shown.filter(r=>r.name.toLowerCase().includes(recipeQuery.toLowerCase()));$('#recipeCards').innerHTML=shown.map(r=>{let t=r.items.reduce((a,x)=>a+x.grams,0);return`<div class="rcard" onclick="editRecipe('${r.id}')"><div class="rcardTop"><span class="badge">${cats[r.category]||'Non classificata'}</span><span>${fmt(t,0)} g</span></div><h3>${r.name}</h3><p>${r.items.length} ingredienti</p><button onclick="event.stopPropagation();openR('${r.id}')">Apri nel bilanciatore</button></div>`}).join('')||'<div class="empty">Nessuna ricetta trovata.</div>'}
window.renderRecipes=renderRecipes;window.openR=id=>{switchView('balance');$('#recipeLoad').value=id;loadRecipe(id)};
window.editRecipe=id=>{let r=allRecipes().find(x=>x.id===id);if(!r)return;openModal(`<h2>Modifica ricetta</h2><form id="recipeForm"><label>Nome<input name="name" required value="${r.name}"></label><label>Categoria<select name="category">${profileOptions(r.category,true)}</select></label><label>Note generali<textarea name="notes" placeholder="Note stabili della ricetta, non note di produzione">${r.notes||''}</textarea></label><div class="modalActions"><button type="button" class="danger" id="deleteRecipe">Elimina ricetta</button><button type="button" id="balanceRecipe">Apri nel bilanciatore</button><button class="primary" type="submit">Salva modifiche</button></div></form>`);$('#recipeForm').onsubmit=e=>{e.preventDefault();let fd=new FormData(e.target),users=userRecipes(),u=users.find(x=>x.id===id);if(u){u.name=fd.get('name').trim();u.category=fd.get('category');u.notes=fd.get('notes').trim();setJSON(KEYS.recipes,users)}else{let m=recipeMeta();m[id]={...(m[id]||{}),name:fd.get('name').trim(),category:fd.get('category'),notes:fd.get('notes').trim()};setJSON(KEYS.recipeMeta,m)}closeModal();fillRecipeSelect();renderRecipes()};$('#balanceRecipe').onclick=()=>{closeModal();openR(id)};$('#deleteRecipe').onclick=()=>{if(!confirm(`Eliminare la ricetta "${r.name}"? L'operazione non può essere annullata.`))return;let users=userRecipes();if(users.some(x=>x.id===id)){setJSON(KEYS.recipes,users.filter(x=>x.id!==id))}else{let m=recipeMeta();m[id]={...(m[id]||{}),deleted:true};setJSON(KEYS.recipeMeta,m)}let prod=getJSON(KEYS.productions,{});delete prod[id];setJSON(KEYS.productions,prod);if(state.loadedId===id)newRecipe();closeModal();fillRecipeSelect();renderRecipes()}};

function renderProductionHistory(){let box=$('#productionHistory');if(!box)return;let logs=state.loadedId?(getJSON(KEYS.productions,{})[state.loadedId]||[]):[];$('#productionHint').textContent=state.loadedId?'Ogni registrazione conserva data, quantità e condizioni di servizio.':'Salva o carica una ricetta per creare lo storico.';box.innerHTML=logs.length?logs.slice().reverse().map(x=>`<div class="historyItem"><small>${new Date(x.date).toLocaleString('it-IT')} · ${fmt(x.grams,0)} g · ${x.temp} °C · ${x.service}</small><div>${x.note}</div></div>`).join(''):state.loadedId?'<div class="empty">Nessuna nota di produzione registrata.</div>':''}
function renderProfiles(){let labels={sugars:'Zuccheri %',fat:'Grassi %',msnf:'MSNF %',solids:'Solidi totali %',pac:'PAC',pod:'POD'};$('#profileEditor').innerHTML=Object.entries(draftProfiles).map(([id,p])=>`<div class="profilebox"><h3>${p.label}</h3><div class="rangegrid"><b>Parametro</b><b>Min</b><b>Max</b>${Object.entries(p.ranges).filter(([k])=>labels[k]).map(([k,r])=>`<span>${labels[k]}</span><input value="${r[0]}" type="number" step=".1" onchange="draftProfiles['${id}'].ranges['${k}'][0]=+this.value;markProfileDirty()"><input value="${r[1]}" type="number" step=".1" onchange="draftProfiles['${id}'].ranges['${k}'][1]=+this.value;markProfileDirty()">`).join('')}</div></div>`).join('')}
window.markProfileDirty=()=>{$('#profileSaveState').textContent='Modifiche non salvate';$('#profileSaveState').className='saveState dirty'};
function openModal(html){$('#modalBody').innerHTML=html;$('#modal').classList.add('open')}function closeModal(){$('#modal').classList.remove('open')}
$('#modalClose').onclick=closeModal;$('#modal').onclick=e=>{if(e.target===$('#modal'))closeModal()};$('#newIngredient').onclick=()=>ingredientModal();$('#addRow').onclick=()=>{state.items.push({ingredientId:'',grams:0});renderFormula()};$('#newRecipe').onclick=newRecipe;$('#recipeLoad').onchange=e=>e.target.value?loadRecipe(e.target.value):newRecipe();$('#profile').onchange=e=>{state.profile=e.target.value;renderMetrics()};$('#service').onchange=e=>{state.service=e.target.value;if(e.target.value==='home'){state.temp=-18;$('#temp').value=-18}else if(e.target.value==='display'){state.temp=-13;$('#temp').value=-13}renderMetrics()};$('#temp').onchange=e=>{state.temp=+e.target.value;state.service='custom';$('#service').value='custom';renderMetrics()};
function scaleTo(target){let{total}=calc();if(!total||target<=0)return;let f=target/total;state.items.forEach(x=>{let i=ing(x.ingredientId),s=i&&(/neutro|stabil|diglicer|sale/i.test(i.name));x.grams=Math.round(x.grams*f*(s?10:1))/(s?10:1)});renderFormula()}$('#scaleBtn').onclick=()=>scaleTo(+$('#totalTarget').value);$('#plus10').onclick=()=>scaleTo(calc().total+10);$('#minus10').onclick=()=>scaleTo(Math.max(10,calc().total-10));$('#notes').oninput=e=>state.notes=e.target.value;$('#saveProduction').onclick=()=>{if(!state.loadedId){alert('Prima salva o carica una ricetta.');return}let note=$('#notes').value.trim();if(!note){alert('Inserisci una nota di produzione.');return}let all=getJSON(KEYS.productions,{});(all[state.loadedId]||(all[state.loadedId]=[])).push({date:new Date().toISOString(),grams:calc().total,temp:state.temp,service:state.service,note});setJSON(KEYS.productions,all);$('#notes').value='';state.notes='';renderProductionHistory()};
$('#saveRecipe').onclick=()=>{let name=prompt('Nome della nuova ricetta:',state.loadedName==='Nuova ricetta'?'':state.loadedName);if(!name)return;let rs=userRecipes();rs.push({id:'u'+Date.now(),name,category:state.profile,items:state.items.filter(x=>x.ingredientId).map(x=>({...x})),notes:'',createdAt:new Date().toISOString()});setJSON(KEYS.recipes,rs);state.loadedId=rs[rs.length-1].id;state.loadedName=name;$('#loadedName').textContent=name;fillRecipeSelect();$('#recipeLoad').value=state.loadedId;renderRecipes();renderProductionHistory();alert('Ricetta salvata nel browser.')};
$('#baseMode').onclick=()=>{state.advanced=false;$('#baseMode').classList.add('active');$('#advMode').classList.remove('active');renderMetrics()};$('#advMode').onclick=()=>{state.advanced=true;$('#advMode').classList.add('active');$('#baseMode').classList.remove('active');renderMetrics()};
$('#saveProfiles').onclick=()=>{profiles=clone(draftProfiles);setJSON(KEYS.profiles,profiles);$('#profileSaveState').textContent='Profili salvati';$('#profileSaveState').className='saveState saved';fillRecipeSelect();renderMetrics();renderRecipes()};$('#resetProfiles').onclick=()=>{if(!confirm('Ripristinare i range predefiniti?'))return;draftProfiles=clone(DEFAULT_PROFILES);renderProfiles();markProfileDirty()};
function switchView(v){document.querySelectorAll('.nav,.view').forEach(x=>x.classList.remove('active'));document.querySelector(`.nav[data-view="${v}"]`).classList.add('active');$('#'+v).classList.add('active');let titles={balance:['Bilanciamento','Formula, controlla, scala e salva le tue ricette.'],ingredients:['Ingredienti','Il database tecnico delle tue materie prime.'],recipes:['Ricettario','Organizza e riapri le formule già collaudate.'],settings:['Profili & range','Personalizza i target tecnici per categoria.']};$('#pageTitle').textContent=titles[v][0];$('#pageSub').textContent=titles[v][1]}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$('#ingSearch').oninput=e=>renderIngredients(e.target.value);$('#recipeSearch').oninput=e=>{recipeQuery=e.target.value;renderRecipes()};
fillRecipeSelect();renderIngredients();renderRecipes();renderProfiles();newRecipe();
