const D=window.ICEC_DATA;
const KEYS={recipes:'icec_user_recipes_v2',ingredients:'icec_ingredients_v2',profiles:'icec_profiles_v2',recipeMeta:'icec_recipe_meta_v2',productions:'icec_productions_v3',feedbacks:'icec_feedbacks_v4'};
const ENGINE_VERSION='0.8.1';
const DEFAULT_PROFILES={
 cream:{label:'Creme / base latte',ranges:{sugars:[18,22],fat:[7,16],msnf:[7,12],solids:[37,46],pac:[22,28],pod:[16,22]}},
 choc:{label:'Cioccolato',ranges:{sugars:[18,23],fat:[6,14],msnf:[5,11],solids:[38,48],pac:[22,29],pod:[16,23]}},
 nuts:{label:'Frutta secca',ranges:{sugars:[17,22],fat:[8,16],msnf:[5,11],solids:[38,48],pac:[22,29],pod:[15,22]}},
 fruit:{label:'Frutta',ranges:{sugars:[22,24],fat:[0,10],msnf:[0,7],solids:[32,42],pac:[26,34],pod:[20,26]}},
 sorbet:{label:'Sorbetto',ranges:{sugars:[22,28],fat:[0,3],msnf:[0,2],solids:[30,40],pac:[27,35],pod:[21,28]}},
 granita:{label:'Granita',ranges:{sugars:[14,24],fat:[0,3],msnf:[0,2],solids:[14,30],pac:[18,32],pod:[14,25]}}
};
const clone=o=>JSON.parse(JSON.stringify(o)), $=s=>document.querySelector(s), fmt=(n,d=1)=>Number(n||0).toLocaleString('it-IT',{minimumFractionDigits:d,maximumFractionDigits:d});
const getJSON=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}, setJSON=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
let profiles=getJSON(KEYS.profiles,clone(DEFAULT_PROFILES));
function normalizeProfiles(ps){Object.values(ps).forEach(p=>{p.display=p.display||{};p.evaluate=p.evaluate||{};Object.keys(p.ranges).forEach(k=>{if(p.display[k]==null)p.display[k]=!(p.label==='Granita'&&['fat','msnf'].includes(k));if(p.evaluate[k]==null)p.evaluate[k]=p.display[k]});if(p.display.pacWater==null)p.display.pacWater=true;if(p.evaluate.pacWater==null)p.evaluate.pacWater=false;p.source=p.source||'Standard IceC · riferimento professionale + personalizzazione utente'});return ps}
profiles=normalizeProfiles(profiles); let draftProfiles=clone(profiles);
let ingredientDB=getJSON(KEYS.ingredients,null)||D.ingredients.map(i=>({...i,_legacy:true}));
let state={items:[],advanced:false,profile:'cream',service:'display',temp:-13,loadedId:null,loadedName:'Nuova ricetta',dirty:false};
function userRecipes(){return getJSON(KEYS.recipes,[])} function recipeMeta(){return getJSON(KEYS.recipeMeta,{})}
function allRecipes(){let meta=recipeMeta();return [...D.recipes.filter(r=>!meta[r.id]?.deleted).map(r=>({...r,name:meta[r.id]?.name||r.name,category:meta[r.id]?.category||'unclassified',notes:meta[r.id]?.notes||r.notes||'',items:meta[r.id]?.itemsOverride||r.items})),...userRecipes()]}
function ing(id){return ingredientDB.find(x=>x.id===id)}
function missingFields(i){if(!i)return ['ingrediente'];let miss=[]; if(i.cost==null||(i._legacy&&i.cost===0&&!/^(acqua|sale)$/i.test(i.name)))miss.push('costo'); ['kcal','carbs','sugars','fat','protein','solids','water','pac','pod'].forEach(k=>{if(i[k]==null)miss.push(k)}); if(i._legacy&&Object.values(i).filter(v=>v===0).length>=8&&!/^acqua$/i.test(i.name))miss.push('dati tecnici da verificare'); return [...new Set(miss)]}
const SUGAR_KEYS=['sucrose','dextrose','fructose','lactose','maltose','invertSugar'];
const SUGAR_LABELS={sucrose:'Saccarosio',dextrose:'Destrosio / glucosio',fructose:'Fruttosio',lactose:'Lattosio',maltose:'Maltosio',invertSugar:'Zucchero invertito'};
function sugarDetail(i){if(!i)return {known:0,parts:[]};let parts=SUGAR_KEYS.filter(k=>i[k]!=null&&+i[k]>0).map(k=>({key:k,label:SUGAR_LABELS[k],value:+i[k]}));return {known:parts.reduce((a,x)=>a+x.value,0),parts}}
function formulaSugarCoverage(){let sugarMass=0,knownMass=0,unknown=[];state.items.forEach(x=>{let i=ing(x.ingredientId);if(!i||!x.grams)return;let totalSugar=Math.max(0,+i.sugars||0),d=sugarDetail(i);sugarMass+=x.grams*totalSugar/100;knownMass+=x.grams*Math.min(totalSugar,d.known)/100;if(totalSugar>.05&&d.known<totalSugar*.8)unknown.push(i.name)});return {coverage:sugarMass?Math.min(100,knownMass/sugarMass*100):100,unknown:[...new Set(unknown)],sugarMass,knownMass}}
function sugarMix(){let total=calc().total,out={};SUGAR_KEYS.forEach(k=>out[k]=0);if(!total)return out;state.items.forEach(x=>{let i=ing(x.ingredientId);if(!i)return;SUGAR_KEYS.forEach(k=>{if(i[k]!=null)out[k]+=x.grams*(+i[k])/100})});SUGAR_KEYS.forEach(k=>out[k]=out[k]/total*100);return out}
function confidenceLabel(c){return c>=85?'Alta':c>=50?'Media':'Limitata'}
function calc(){let total=state.items.reduce((a,x)=>a+(+x.grams||0),0),m={kcal:0,carbs:0,sugars:0,fat:0,protein:0,fiber:0,salt:0,msnf:0,solids:0,water:0,pac:0,pod:0,cost:0};state.items.forEach(x=>{let i=ing(x.ingredientId);if(!i)return;Object.keys(m).forEach(k=>{let v=i[k];if(v==null)return;if(k==='cost')m[k]+=x.grams*v/1000;else m[k]+=x.grams*v/100})});if(total){['carbs','sugars','fat','protein','fiber','salt','msnf','solids','water','pac','pod'].forEach(k=>m[k]=m[k]/total*100);m.kcal=m.kcal/total*100}return{total,m}}
function serviceRange(key,base){return base} // v0.6: niente conversioni lineari temperatura→PAC; il contesto termico resta separato dai target empirici.
function status(v,r){if(v>=r[0]&&v<=r[1])return'good';let dist=v<r[0]?(r[0]-v)/(r[1]||1):(v-r[1])/(r[1]||1);return dist<.12?'warn':'bad'}
function profileOptions(selected,allowUn=true){return (allowUn?'<option value="unclassified">Non classificata</option>':'')+Object.entries(profiles).map(([k,p])=>`<option value="${k}" ${k===selected?'selected':''}>${p.label}</option>`).join('')}
function renderFormula(){let{total}=calc();renderFormulaIdentity();$('#formula').innerHTML=state.items.length?state.items.map((x,n)=>`<div class="frow ${x.ingredientId&&missingFields(ing(x.ingredientId)).length?'hasMissing':''}"><select onchange="setIng(${n},this.value)"><option value="">Seleziona ingrediente…</option>${ingredientDB.map(i=>`<option value="${i.id}" ${i.id===x.ingredientId?'selected':''}>${i.name}</option>`).join('')}</select><input type="number" step="0.1" value="${x.grams||''}" placeholder="g" onchange="setG(${n},this.value)"><div class="pct">${total?fmt(x.grams/total*100):0}%</div><button class="del" onclick="delRow(${n})">×</button></div>`).join(''):'<div class="empty">Aggiungi il primo ingrediente per iniziare.</div>';$('#totalG').textContent=fmt(total,1)+' g';$('#totalTarget').value=Math.round(total);renderMetrics()}
function markRecipeDirty(){if(state.loadedId)state.dirty=true;renderFormulaIdentity()}function renderFormulaIdentity(){let n=$('#formulaRecipeName'),st=$('#formulaRecipeState');if(!n||!st)return;n.textContent=state.loadedId?state.loadedName:'Nuova formula';st.textContent=state.loadedId?(state.dirty?'Modifiche non salvate':'Ricetta salvata'):'Non salvata';st.classList.toggle('dirty',state.dirty||!state.loadedId)}
window.setIng=(n,v)=>{state.items[n].ingredientId=v;markRecipeDirty();renderFormula()};window.setG=(n,v)=>{state.items[n].grams=Math.max(0,+v||0);markRecipeDirty();renderFormula()};window.delRow=n=>{state.items.splice(n,1);markRecipeDirty();renderFormula()};
function quality(){let issues=[];state.items.forEach(x=>{if(!x.ingredientId)return issues.push('Una riga non ha ancora un ingrediente selezionato.');let i=ing(x.ingredientId),m=missingFields(i);if(m.length)issues.push(`${i.name}: ${m.join(', ')}`);if(i&&i.solids!=null&&i.water!=null&&Math.abs((i.solids+i.water)-100)>2)issues.push(`${i.name}: solidi + acqua = ${fmt(i.solids+i.water,1)}% (verifica coerenza).`);if(i&&i.sugars!=null&&i.carbs!=null&&i.sugars>i.carbs+.2)issues.push(`${i.name}: zuccheri superiori ai carboidrati (verifica etichetta).`) });return [...new Set(issues)]}
const METRIC_INFO={
 sugars:{title:'Zuccheri',kind:'Calcolo compositivo',text:'Percentuale di zuccheri nella miscela. Influenza dolcezza, solidi e comportamento al congelamento; il solo totale non descrive quali zuccheri sono presenti.'},
 fat:{title:'Grassi',kind:'Calcolo compositivo',text:'Quota lipidica della miscela. Contribuisce a corpo, cremosità e percezione aromatica; il target dipende dalla famiglia di prodotto.'},
 protein:{title:'Proteine',kind:'Calcolo compositivo',text:'Quota proteica stimata dagli ingredienti. Contribuisce a struttura ed emulsione, ma non viene valutata se il profilo non definisce un target.'},
 msnf:{title:'MSNF',kind:'Calcolo compositivo',text:'Solidi del latte non grassi. È un indicatore tecnico utile soprattutto nelle basi latte e comprende componenti come lattosio, proteine e sali minerali.'},
 solids:{title:'Solidi totali',kind:'Calcolo compositivo',text:'Tutto ciò che nella miscela non è acqua. Il valore totale è importante, ma la natura dei solidi resta determinante per la struttura.'},
 water:{title:'Acqua',kind:'Calcolo compositivo',text:'Quota d’acqua della miscela. Durante il congelamento solo una parte diventa ghiaccio; IceC non stima ancora la curva di congelamento.'},
 pac:{title:'PAC miscela',kind:'Indicatore tecnico',text:'Indice convenzionale del potere anticongelante della formulazione. Va letto insieme ad acqua, composizione degli zuccheri e temperatura, non come previsione autonoma della morbidezza.'},
 pacWater:{title:'PAC su acqua',kind:'Indicatore tecnico',text:'PAC della miscela normalizzato rispetto alla quota d’acqua. È utile per confrontare ricette con quantità d’acqua differenti; non ha un singolo range universale valido per ogni prodotto e temperatura.'},
 pod:{title:'POD',kind:'Indicatore tecnico',text:'Indice convenzionale del potere dolcificante. Aiuta a separare il tema della dolcezza da quello anticongelante: zuccheri diversi possono avere rapporti PAC/POD differenti.'},
 kcal:{title:'Energia',kind:'Calcolo compositivo',text:'Valore energetico stimato per 100 g sulla base dei dati degli ingredienti.'},
 carbs:{title:'Carboidrati',kind:'Calcolo compositivo',text:'Carboidrati totali dichiarati o stimati dagli ingredienti.'},fiber:{title:'Fibre',kind:'Calcolo compositivo',text:'Fibre totali stimate nella miscela.'},salt:{title:'Sale',kind:'Calcolo compositivo',text:'Sale totale stimato nella miscela.'}
};
window.explainMetric=k=>{let x=METRIC_INFO[k];if(!x)return;openModal(`<div class="eyebrow">${x.kind.toUpperCase()}</div><h2>${x.title}</h2><p class="explainText">${x.text}</p><div class="explainLegend"><b>Come leggere IceC</b><span><i class="dot calc"></i> Calcolo: deriva dai dati della formula.</span><span><i class="dot target"></i> Target: intervallo empirico del profilo selezionato.</span><span><i class="dot prediction"></i> Predizione: stima del comportamento; non ancora disponibile per consistenza/acqua congelata.</span></div>`)};
function smartDiagnostics(values,p){let out=[];let add=(level,title,text)=>out.push({level,title,text});let range=k=>p.ranges[k], low=k=>range(k)&&values[k]<range(k)[0], high=k=>range(k)&&values[k]>range(k)[1],cov=formulaSugarCoverage(),mix=sugarMix();
 if(low('pac')&&high('pod')) add('warn','PAC basso con POD già alto','La ricetta combina potere anticongelante basso e dolcezza già elevata. Aumentare semplicemente il saccarosio rischierebbe di peggiorare la dolcezza: la leva da studiare è la distribuzione degli zuccheri, se i dati disponibili lo consentono.');
 else if(low('pac')) add('warn','PAC sotto il target','Il potere anticongelante convenzionale è basso. Se il prodotto risulta duro, valuta la distribuzione degli zuccheri prima di aumentare indiscriminatamente la quantità totale.');
 if(high('pac')&&low('pod')) add('info','PAC alto con POD contenuto','La formulazione ha molto effetto anticongelante rispetto alla dolcezza. Verifica che sia intenzionale e coerente con temperatura e servizio.');
 else if(high('pac')) add('warn','PAC sopra il target','Il potere anticongelante convenzionale è elevato. La miscela potrebbe restare più morbida, ma IceC non converte ancora il dato in consistenza prevista.');
 if(high('sugars')) add('warn','Zuccheri sopra il target','La miscela può risultare troppo dolce. Prima di ridurre genericamente gli zuccheri considera la loro composizione e il rapporto PAC/POD.');
 if(low('sugars')) add('warn','Zuccheri sotto il target','Una quota zuccherina bassa può ridurre dolcezza e contribuire a una struttura più dura. Va letta insieme a PAC e solidi totali.');
 if(high('solids')) add('info','Solidi totali elevati','Una miscela molto concentrata può diventare pesante o meno fluida. Conta anche la natura dei solidi, non solo il totale.');
 if(low('solids')) add('info','Solidi totali bassi','La miscela contiene relativamente molta acqua. Può incidere sulla struttura e sulla quota di ghiaccio, che IceC non quantifica ancora.');
 if(high('fat')&&['cream','choc','nuts'].includes(state.profile)) add('info','Grassi sopra il target','La quota lipidica è elevata per il profilo selezionato. Verifica corpo, fusione e percezione aromatica.');
 if(low('fat')&&['cream','choc','nuts'].includes(state.profile)) add('info','Grassi sotto il target','Per questo profilo la quota lipidica è bassa. Valuta corpo e cremosità insieme a solidi e proteine.');
 if(['sorbet','fruit'].includes(state.profile)&&values.fat>3) add('info','Grassi presenti in un profilo a base acqua','Verifica che la presenza lipidica sia intenzionale: in sorbetti e molte formulazioni frutta il ruolo strutturale è diverso da una base latte.');
 if(state.profile==='granita') add('context','Lettura specifica Granita','Per la granita IceC privilegia zuccheri, solidi e PAC; grassi e MSNF possono essere nascosti o esclusi dalla valutazione nel profilo. La tessitura finale dipende anche dal processo di congelamento e rimescolamento.');
 if(cov.coverage<85&&values.sugars>0) add('context','Analisi zuccheri parziale',`IceC conosce nel dettaglio circa il ${fmt(cov.coverage,0)}% degli zuccheri della formula. I suggerimenti PAC/POD restano prudenziali finché non completi la composizione zuccherina degli ingredienti principali.`);
 if(state.service==='home') add('context','Contesto freezer domestico',`Stai valutando la ricetta a ${fmt(state.temp,0)} °C. La temperatura è un contesto di utilizzo: non viene trasformata linearmente in un PAC obiettivo.`);
 return out.slice(0,7)}
function renderMetrics(){let{total,m}=calc(),p=profiles[state.profile]||profiles.cream,waterPct=m.water||0,pacWater=waterPct>0?m.pac/waterPct*100:null,allKeys=state.advanced?['sugars','fat','protein','msnf','solids','water','pac','pacWater','pod','kcal','carbs','fiber','salt']:['sugars','fat','protein','solids','water','pac','pod','kcal'],keys=allKeys.filter(k=>p.display?.[k]!==false);let labels={sugars:'Zuccheri',fat:'Grassi',protein:'Proteine',msnf:'MSNF',solids:'Solidi totali',water:'Acqua',pac:'PAC miscela',pacWater:'PAC su acqua',pod:'POD',kcal:'kcal / 100g',carbs:'Carboidrati',fiber:'Fibre',salt:'Sale'},values={...m,pacWater},scored=[];
 $('#metrics').innerHTML=keys.map(k=>{let r=p.ranges[k]?serviceRange(k,p.ranges[k]):null,evaluated=r&&p.evaluate?.[k]!==false,s=evaluated?status(values[k],r):'info';if(evaluated)scored.push(s);let unit=['pac','pacWater','pod','kcal'].includes(k)?'':'%';return`<div class="metric ${s}"><div class="metricTitle"><small>${labels[k]}</small><button class="infoBtn" onclick="explainMetric('${k}')" title="Spiegazione">i</button></div><b>${values[k]==null?'—':fmt(values[k],k==='salt'?2:1)}${values[k]==null?'':unit}</b>${r?`<em><span class="typeTag targetTag">Target empirico</span> ${fmt(r[0],0)}–${fmt(r[1],0)}</em>`:`<em><span class="typeTag calcTag">Calcolato</span></em>`}</div>`}).join('');
 let good=scored.filter(x=>x==='good').length,score=scored.length?Math.round(good/scored.length*100):0;$('#ring').textContent=score;$('#scoreText').textContent=!total?'In attesa':!scored.length?'Solo informativo':score>=85?'Ben bilanciata':score>=60?'Da rifinire':'Da ribilanciare';$('#scoreDetail').textContent=total?`${good}/${scored.length} parametri valutati nel range · ${p.label}`:'Aggiungi ingredienti alla formula.';
 let issues=quality();$('#qualityAlert').innerHTML=issues.length?`<div class="quality"><b>Completezza dati: attenzione</b><span>${issues.length} segnalazion${issues.length===1?'e':'i'}. Alcuni risultati possono essere incompleti.</span><button onclick="showQuality()">Dettagli</button></div>`:'';
 let diag=smartDiagnostics(values,p);$('#advice').innerHTML=total?(diag.length?diag.map(x=>`<div class="diagnostic ${x.level}"><b>${x.title}</b><span>${x.text}</span></div>`).join(''):'<div class="diagnostic good"><b>Nessuna criticità evidente</b><span>I parametri attualmente valutati rientrano nei target del profilo. Il risultato sensoriale resta da verificare sul prodotto reale.</span></div>'):'Il motore di bilanciamento si attiverà con la formula.';
 let missingCost=state.items.some(x=>x.ingredientId&&missingFields(ing(x.ingredientId)).includes('costo'));$('#costTotal').textContent=(missingCost?'≥ ':'')+'€ '+fmt(m.cost,2)+(missingCost?' · incompleto':'');$('#costKg').textContent=(missingCost?'≥ ':'')+'€ '+fmt(total?m.cost/total*1000:0,2)+(missingCost?' · incompleto':'');renderScience(total,m,pacWater)}
function renderScience(total,m,pacWater){let panel=$('#sciencePanel'),box=$('#scienceMetrics'),note=$('#scienceNote');if(!panel||!box)return;panel.style.display=state.advanced?'block':'none';if(!state.advanced)return;if(!total){box.innerHTML='<div class="empty">Aggiungi ingredienti per attivare gli indicatori scientifici.</div>';note.textContent='';return}let cov=formulaSugarCoverage(),mix=sugarMix(),known=Object.entries(mix).filter(([,v])=>v>.01);box.innerHTML=`<div class="scienceKpi"><small>Acqua miscela <button class="infoBtn" onclick="explainMetric('water')">i</button></small><b>${fmt(m.water)}%</b><span class="typeTag calcTag">Calcolo</span></div><div class="scienceKpi"><small>PAC su acqua <button class="infoBtn" onclick="explainMetric('pacWater')">i</button></small><b>${pacWater==null?'—':fmt(pacWater,1)}</b><span class="typeTag technicalTag">Indicatore</span></div><div class="scienceKpi"><small>Copertura zuccheri</small><b>${fmt(cov.coverage,0)}%</b><span class="typeTag ${cov.coverage>=85?'calcTag':'targetTag'}">Confidenza ${confidenceLabel(cov.coverage)}</span></div>`;
 let mixHtml=known.length?known.map(([k,v])=>`<span><b>${SUGAR_LABELS[k]}</b> ${fmt(v,2)}%</span>`).join(''):'<span>Composizione zuccherina dettagliata non ancora disponibile.</span>';
 note.innerHTML=`<div class="scienceDetail"><b>Composizione zuccherina nota</b><div class="sugarMix">${mixHtml}</div></div>${cov.unknown.length?`<div class="scienceWarning"><b>Analisi PAC/POD parziale.</b> Completa la composizione zuccherina di: ${cov.unknown.slice(0,5).join(', ')}${cov.unknown.length>5?'…':''}.</div>`:''}<b>Interpretazione prudenziale.</b> Il PAC su acqua resta un indicatore comparativo. IceC v${ENGINE_VERSION} non calcola ancora percentuale di acqua congelata o consistenza alla temperatura selezionata (${fmt(state.temp,0)} °C).`}
function newRecipe(){state={...state,items:[],profile:'cream',loadedId:null,loadedName:'Nuova ricetta',dirty:false};$('#recipeLoad').value='';$('#profile').value=state.profile;$('#loadedName').textContent=state.loadedName;renderFormula();renderFeedbackHistory();renderSaveActions()}
function loadRecipe(id){let r=allRecipes().find(x=>x.id===id);if(!r)return;state.items=r.items.filter(x=>x.ingredientId).map(x=>({...x}));state.loadedId=id;state.loadedName=r.name;state.dirty=false;state.profile=r.category&&r.category!=='unclassified'?r.category:'cream';$('#profile').value=state.profile;$('#loadedName').textContent=r.name;renderFormula();renderFeedbackHistory();renderSaveActions()}
function fillRecipeSelect(){let rs=allRecipes();$('#recipeLoad').innerHTML='<option value="">— Carica una ricetta —</option>'+rs.map(r=>`<option value="${r.id}">${r.name}</option>`).join('');$('#dbcount').textContent=`${ingredientDB.length} ingredienti · ${rs.length} ricette`;$('#profile').innerHTML=profileOptions(state.profile,false)}
function completeness(i){let m=missingFields(i);return m.length?`<span class="badge warnBadge">${m.length} da verificare</span>`:''}
function renderIngredients(q=''){let rows=ingredientDB.filter(i=>i.name.toLowerCase().includes(q.toLowerCase()));$('#ingredientList').innerHTML=rows.map(i=>`<button class="ingredientRow" onclick="editIngredient('${i.id}')"><div><b>${i.name}</b><small>${i.category||'Categoria non impostata'}</small></div><div class="miniStats"><span>Zuccheri <b>${i.sugars==null?'—':fmt(i.sugars)}%</b></span><span>Grassi <b>${i.fat==null?'—':fmt(i.fat)}%</b></span><span>PAC <b>${i.pac==null?'—':fmt(i.pac)}</b></span><span>POD <b>${i.pod==null?'—':fmt(i.pod)}</b></span><span>€/kg <b>${i.cost==null?'—':fmt(i.cost,2)}</b></span></div>${completeness(i)}<span class="chev">›</span></button>`).join('')||'<div class="empty">Nessun ingrediente trovato.</div>'}
window.editIngredient=id=>ingredientModal(ing(id));
function sugarAutoProposal(i){
 let name=(i?.name||'').toLowerCase(), sugars=i?.sugars==null?null:+i.sugars, p={};
 if(sugars==null)return null;
 if(/saccarosio|zucchero\s*\(saccarosio\)|^zucchero$/.test(name))p.sucrose=sugars;
 else if(/destrosio|dextrose/.test(name))p.dextrose=sugars;
 else if(/fruttosio|fructose/.test(name))p.fructose=sugars;
 else if(/lattosio|lactose/.test(name))p.lactose=sugars;
 else if(/maltosio|maltose/.test(name))p.maltose=sugars;
 else if(/zucchero invertito|invert sugar/.test(name))p.invertSugar=sugars;
 else if(/latte|panna|siero|whey/.test(name))p.lactose=sugars;
 return Object.keys(p).length?p:null;
}
function ingredientModal(i=null){
 let baseFields=[['kcal','kcal'],['carbs','Carboidrati %'],['sugars','Zuccheri %'],['fat','Grassi %'],['protein','Proteine %'],['fiber','Fibre %'],['salt','Sale %'],['msnf','MSNF %'],['solids','Solidi %'],['water','Acqua %'],['pac','PAC'],['pod','POD'],['cost','Costo €/kg']],
 sugarFields=[['sucrose','Saccarosio %'],['dextrose','Destrosio / glucosio %'],['fructose','Fruttosio %'],['lactose','Lattosio %'],['maltose','Maltosio %'],['invertSugar','Zucchero invertito %']],miss=i?missingFields(i):[], hasSugar=i&&SUGAR_KEYS.some(k=>i[k]!=null), sugarSource=i?.sugarDataSource||'unknown';
 openModal(`<h2>${i?'Modifica ingrediente':'Nuovo ingrediente'}</h2>${miss.length?`<div class="quality"><b>Dati da completare</b><span>${miss.join(', ')}</span></div>`:''}<form id="ingForm"><label>Nome<input name="name" required value="${i?.name||''}"></label><label>Categoria<input name="category" value="${i?.category||''}" placeholder="Es. Latte, Zucchero, Frutta secca"></label><div class="formGrid">${baseFields.map(([k,l])=>`<label class="${miss.includes(k)?'missingField':''}">${l}<input name="${k}" type="number" step="0.01" value="${i?.[k]??''}" placeholder="Dato non disponibile"></label>`).join('')}</div>
 <div class="advancedToggleRow"><div><b>Dati avanzati</b><small>Composizione zuccherina opzionale. I campi vuoti significano “sconosciuto”, non zero.</small></div><label class="switch"><input id="advancedIngredientToggle" type="checkbox" ${hasSugar?'checked':''}><span></span></label></div>
 <div id="advancedIngredientFields" class="advancedIngredientFields ${hasSugar?'':'hidden'}"><div class="advancedHead"><div><b>Composizione zuccherina</b><small>Usata per aumentare la confidenza dell'analisi PAC/POD.</small></div><button type="button" id="autoSugar">Proponi dati automatici</button></div><div class="formGrid">${sugarFields.map(([k,l])=>`<label>${l}<input name="${k}" type="number" step="0.01" value="${i?.[k]??''}" placeholder="— sconosciuto"></label>`).join('')}</div><label class="sourceField">Provenienza dei dati<select name="sugarDataSource"><option value="unknown" ${sugarSource==='unknown'?'selected':''}>Sconosciuta / non specificata</option><option value="declared" ${sugarSource==='declared'?'selected':''}>Dichiarata dal produttore</option><option value="calculated" ${sugarSource==='calculated'?'selected':''}>Calcolata</option><option value="estimated" ${sugarSource==='estimated'?'selected':''}>Stimata / riferimento tecnico</option></select></label><div id="sugarHint" class="sugarHint"></div></div>
 <div class="modalActions">${i?'<button type="button" class="danger" id="deleteIng">Elimina</button><button type="button" id="duplicateIng">Duplica</button>':''}<button class="primary" type="submit">Salva ingrediente</button></div></form>`);
 const form=$('#ingForm'), adv=$('#advancedIngredientFields'), toggle=$('#advancedIngredientToggle');
 toggle.onchange=()=>adv.classList.toggle('hidden',!toggle.checked);
 form.querySelectorAll('.formGrid:first-of-type input[type=number]').forEach(inp=>{const lab=inp.closest('label');const refresh=()=>lab.classList.toggle('missingField',inp.value==='');inp.addEventListener('input',refresh);refresh()});
 $('#autoSugar').onclick=()=>{let draft={name:form.elements.name.value,sugars:form.elements.sugars.value===''?null:+form.elements.sugars.value},proposal=sugarAutoProposal(draft),hint=$('#sugarHint');if(!proposal){hint.innerHTML='<b>Nessuna proposta sicura.</b> IceC non deduce la composizione di un prodotto complesso senza informazioni sufficienti.';return}SUGAR_KEYS.forEach(k=>form.elements[k].value=proposal[k]??'');form.elements.sugarDataSource.value='calculated';hint.innerHTML='<b>Proposta compilata.</b> Verifica i valori prima di salvare. La proposta deriva dal tipo/nome dell’ingrediente e dagli zuccheri totali.'};
 form.onsubmit=e=>{e.preventDefault();let fd=new FormData(e.target),obj={id:i?.id||'ui'+Date.now(),_legacy:false};for(let[k,v]of fd.entries())obj[k]=k==='name'||k==='category'||k==='sugarDataSource'?v.trim():(v===''?null:+v);if(!toggle.checked){SUGAR_KEYS.forEach(k=>obj[k]=i?.[k]??null);obj.sugarDataSource=i?.sugarDataSource||'unknown'}let ix=ingredientDB.findIndex(x=>x.id===obj.id);if(ix>=0)ingredientDB[ix]=obj;else ingredientDB.push(obj);setJSON(KEYS.ingredients,ingredientDB);closeModal();renderIngredients($('#ingSearch').value);renderFormula();fillRecipeSelect()};
 if(i){$('#duplicateIng').onclick=()=>{closeModal();ingredientModal({...i,id:null,name:i.name+' copia',_legacy:false})};$('#deleteIng').onclick=()=>{let used=allRecipes().filter(r=>r.items.some(x=>x.ingredientId===i.id));if(used.length){alert(`Ingrediente usato in ${used.length} ricett${used.length===1?'a':'e'}. Rimuovilo prima dalle ricette.`);return}if(!confirm(`Eliminare definitivamente "${i.name}"?`))return;ingredientDB=ingredientDB.filter(x=>x.id!==i.id);setJSON(KEYS.ingredients,ingredientDB);closeModal();renderIngredients($('#ingSearch').value);fillRecipeSelect()}}
}
function renderRecipes(filter=recipeFilter){recipeFilter=filter;let rs=allRecipes(),cats={unclassified:'Non classificata',...Object.fromEntries(Object.entries(profiles).map(([k,v])=>[k,v.label]))};$('#recipeFilters').innerHTML=['all',...Object.keys(cats)].map(k=>`<button class="chip ${k===recipeFilter?'active':''}" onclick="renderRecipes('${k}')">${k==='all'?'Tutte':cats[k]}</button>`).join('');let shown=recipeFilter==='all'?rs:rs.filter(r=>r.category===recipeFilter);shown=shown.filter(r=>r.name.toLowerCase().includes(recipeQuery.toLowerCase()));$('#recipeCards').innerHTML=shown.map(r=>{let t=r.items.reduce((a,x)=>a+x.grams,0);return`<div class="rcard" onclick="editRecipe('${r.id}')"><div class="rcardTop"><span class="badge">${cats[r.category]||'Non classificata'}</span><span>${fmt(t,0)} g</span></div><h3>${r.name}</h3><p>${r.items.length} ingredienti</p><button onclick="event.stopPropagation();openR('${r.id}')">Apri nel bilanciatore</button></div>`}).join('')||'<div class="empty">Nessuna ricetta trovata.</div>'}
window.renderRecipes=renderRecipes;window.openR=id=>{switchView('balance');$('#recipeLoad').value=id;loadRecipe(id)};
function feedbacks(){return getJSON(KEYS.feedbacks,{})}
function recipeSnapshot(r){return {name:r.name,category:r.category,items:r.items.map(x=>({...x})),savedAt:new Date().toISOString()}}
function snapshotSummary(snap){let total=(snap.items||[]).reduce((a,x)=>a+(+x.grams||0),0);return `${snap.name||'Ricetta'} · ${fmt(total,0)} g · ${(profiles[snap.category]||{}).label||'Non classificata'}`}
function feedbackHtml(id,editable=false){let logs=(feedbacks()[id]||[]).slice().reverse();if(!logs.length)return '<div class="empty">Nessuna nota post-produzione registrata.</div>';return logs.map(x=>`<div class="historyItem"><div class="historyHead"><small>${new Date(x.date).toLocaleString('it-IT')}</small>${editable?`<button class="danger mini" onclick="deleteFeedback('${id}','${x.id}')">Elimina</button>`:''}</div><div>${x.note}</div><details><summary>Ricetta usata per questa nota</summary><div class="snapshot"><b>${snapshotSummary(x.snapshot)}</b>${(x.snapshot.items||[]).map(it=>`<span>${ing(it.ingredientId)?.name||'Ingrediente non disponibile'} <b>${fmt(it.grams,1)} g</b></span>`).join('')}</div></details></div>`).join('')}
window.deleteFeedback=(recipeId,noteId)=>{if(!confirm('Eliminare questa nota post-produzione?'))return;let all=feedbacks();all[recipeId]=(all[recipeId]||[]).filter(x=>x.id!==noteId);setJSON(KEYS.feedbacks,all);editRecipe(recipeId);if(state.loadedId===recipeId)renderFeedbackHistory()}
window.editRecipe=id=>{let r=allRecipes().find(x=>x.id===id);if(!r)return;openModal(`<h2>Modifica ricetta</h2><form id="recipeForm"><label>Nome<input name="name" required value="${r.name}"></label><label>Categoria<select name="category">${profileOptions(r.category,true)}</select></label><label>Note generali<textarea name="notes" placeholder="Indicazioni stabili della ricetta">${r.notes||''}</textarea></label><div class="modalActions"><button type="button" class="danger" id="deleteRecipe">Elimina ricetta</button><button type="button" id="balanceRecipe">Apri nel bilanciatore</button><button class="primary" type="submit">Salva modifiche</button></div></form><div class="feedbackEditor"><h3>Note post-produzione</h3><p>Registra qui il feedback dopo l'assaggio. Ogni nota conserva una fotografia della ricetta usata in quel momento.</p><textarea id="newFeedback" placeholder="Es. dopo 24 h a −18 °C risulta leggermente duro..."></textarea><button id="addFeedback" class="primary">Aggiungi nota</button><div class="history">${feedbackHtml(id,true)}</div></div>`);$('#recipeForm').onsubmit=e=>{e.preventDefault();let fd=new FormData(e.target),users=userRecipes(),u=users.find(x=>x.id===id);if(u){u.name=fd.get('name').trim();u.category=fd.get('category');u.notes=fd.get('notes').trim();setJSON(KEYS.recipes,users)}else{let m=recipeMeta();m[id]={...(m[id]||{}),name:fd.get('name').trim(),category:fd.get('category'),notes:fd.get('notes').trim()};setJSON(KEYS.recipeMeta,m)}closeModal();fillRecipeSelect();renderRecipes();if(state.loadedId===id)loadRecipe(id)};$('#addFeedback').onclick=()=>{let note=$('#newFeedback').value.trim();if(!note){alert('Inserisci una nota.');return}let current=allRecipes().find(x=>x.id===id),all=feedbacks();(all[id]||(all[id]=[])).push({id:'f'+Date.now(),date:new Date().toISOString(),note,snapshot:recipeSnapshot(current)});setJSON(KEYS.feedbacks,all);editRecipe(id);if(state.loadedId===id)renderFeedbackHistory()};$('#balanceRecipe').onclick=()=>{closeModal();openR(id)};$('#deleteRecipe').onclick=()=>{if(!confirm(`Eliminare la ricetta "${r.name}"? L'operazione non può essere annullata.`))return;let users=userRecipes();if(users.some(x=>x.id===id)){setJSON(KEYS.recipes,users.filter(x=>x.id!==id))}else{let m=recipeMeta();m[id]={...(m[id]||{}),deleted:true};setJSON(KEYS.recipeMeta,m)}let fb=feedbacks();delete fb[id];setJSON(KEYS.feedbacks,fb);if(state.loadedId===id)newRecipe();closeModal();fillRecipeSelect();renderRecipes()}};
function renderFeedbackHistory(){let box=$('#feedbackHistory');if(!box)return;box.innerHTML=state.loadedId?feedbackHtml(state.loadedId,false):'<div class="empty">Carica una ricetta per vedere eventuali note post-produzione.</div>'}

function renderProfiles(){let labels={sugars:'Zuccheri %',fat:'Grassi %',msnf:'MSNF %',solids:'Solidi totali %',pac:'PAC',pod:'POD'};$('#profileEditor').innerHTML=Object.entries(draftProfiles).map(([id,p])=>`<div class="profilebox"><h3>${p.label}</h3><small>${p.source||''}</small><div class="rangegrid"><b>Parametro</b><b>Min</b><b>Max</b><b>Visibile</b><b>Valutato</b>${Object.entries(p.ranges).filter(([k])=>labels[k]).map(([k,r])=>`<span>${labels[k]}</span><input value="${r[0]}" type="number" step=".1" onchange="draftProfiles['${id}'].ranges['${k}'][0]=+this.value;markProfileDirty()"><input value="${r[1]}" type="number" step=".1" onchange="draftProfiles['${id}'].ranges['${k}'][1]=+this.value;markProfileDirty()"><input class="toggle" type="checkbox" ${p.display[k]!==false?'checked':''} onchange="draftProfiles['${id}'].display['${k}']=this.checked;markProfileDirty()"><input class="toggle" type="checkbox" ${p.evaluate[k]!==false?'checked':''} onchange="draftProfiles['${id}'].evaluate['${k}']=this.checked;markProfileDirty()">`).join('')}</div></div>`).join('')}
window.markProfileDirty=()=>{$('#profileSaveState').textContent='Modifiche non salvate';$('#profileSaveState').className='saveState dirty'};
function openModal(html){$('#modalBody').innerHTML=html;$('#modal').classList.add('open')}function closeModal(){$('#modal').classList.remove('open')}
$('#modalClose').onclick=closeModal;$('#modal').onclick=e=>{if(e.target===$('#modal'))closeModal()};$('#newIngredient').onclick=()=>ingredientModal();$('#addRow').onclick=()=>{state.items.push({ingredientId:'',grams:0});markRecipeDirty();renderFormula()};$('#newRecipe').onclick=newRecipe;$('#recipeLoad').onchange=e=>e.target.value?loadRecipe(e.target.value):newRecipe();$('#profile').onchange=e=>{state.profile=e.target.value;markRecipeDirty();renderMetrics()};$('#service').onchange=e=>{state.service=e.target.value;if(e.target.value==='home'){state.temp=-18;$('#temp').value=-18}else if(e.target.value==='display'){state.temp=-13;$('#temp').value=-13}renderMetrics()};$('#temp').onchange=e=>{state.temp=+e.target.value;state.service='custom';$('#service').value='custom';renderMetrics()};
function scaleTo(target){let{total}=calc();if(!total||target<=0)return;markRecipeDirty();let f=target/total;state.items.forEach(x=>{let i=ing(x.ingredientId),s=i&&(/neutro|stabil|diglicer|sale/i.test(i.name));x.grams=Math.round(x.grams*f*(s?10:1))/(s?10:1)});renderFormula()}$('#scaleBtn').onclick=()=>scaleTo(+$('#totalTarget').value);$('#plus10').onclick=()=>scaleTo(calc().total+10);$('#minus10').onclick=()=>scaleTo(Math.max(10,calc().total-10));function recipeNameExists(name,excludeId=null){return allRecipes().some(r=>r.id!==excludeId&&r.name.trim().toLowerCase()===name.trim().toLowerCase())}
function currentRecipePayload(name,id){return {id,name,category:state.profile,items:state.items.filter(x=>x.ingredientId).map(x=>({...x})),notes:'',updatedAt:new Date().toISOString()}}
function saveExistingRecipe(){if(!state.loadedId)return saveAsRecipe();let r=allRecipes().find(x=>x.id===state.loadedId);if(!r)return saveAsRecipe();let users=userRecipes(),u=users.find(x=>x.id===state.loadedId);if(u){u.category=state.profile;u.items=state.items.filter(x=>x.ingredientId).map(x=>({...x}));u.updatedAt=new Date().toISOString();setJSON(KEYS.recipes,users)}else{let meta=recipeMeta();meta[state.loadedId]={...(meta[state.loadedId]||{}),category:state.profile,itemsOverride:state.items.filter(x=>x.ingredientId).map(x=>({...x})),updatedAt:new Date().toISOString()};setJSON(KEYS.recipeMeta,meta)}state.dirty=false;fillRecipeSelect();renderRecipes();renderSaveActions();renderFormulaIdentity();alert('Modifiche salvate.')}
function saveAsRecipe(){let suggested=state.loadedId?state.loadedName+' copia':'';let name=prompt(state.loadedId?'Nome della nuova ricetta:':'Nome della ricetta:',suggested);if(!name)return;name=name.trim();if(!name)return;if(recipeNameExists(name)){alert(`Esiste già una ricetta chiamata "${name}". Scegli un nome diverso.`);return}let rs=userRecipes(),id='u'+Date.now();rs.push({...currentRecipePayload(name,id),createdAt:new Date().toISOString()});setJSON(KEYS.recipes,rs);state.loadedId=id;state.loadedName=name;state.dirty=false;$('#loadedName').textContent=name;fillRecipeSelect();$('#recipeLoad').value=id;renderRecipes();renderFeedbackHistory();renderSaveActions();alert('Nuova ricetta salvata.')}
function renderSaveActions(){if(!$('#saveRecipe'))return;$('#saveRecipe').textContent=state.loadedId?'Salva modifiche':'Salva ricetta…';$('#saveAsRecipe').style.display=state.loadedId?'inline-flex':'none';$('#saveHint').textContent=state.loadedId?`Stai modificando “${state.loadedName}”. Salva le modifiche oppure crea una copia indipendente.`:'Salva la formula nel Ricettario quando hai terminato il bilanciamento.'}
$('#saveRecipe').onclick=saveExistingRecipe;$('#saveAsRecipe').onclick=saveAsRecipe;
$('#baseMode').onclick=()=>{state.advanced=false;$('#baseMode').classList.add('active');$('#advMode').classList.remove('active');renderMetrics()};$('#advMode').onclick=()=>{state.advanced=true;$('#advMode').classList.add('active');$('#baseMode').classList.remove('active');renderMetrics()};
$('#saveProfiles').onclick=()=>{profiles=normalizeProfiles(clone(draftProfiles));setJSON(KEYS.profiles,profiles);$('#profileSaveState').textContent='Profili salvati';$('#profileSaveState').className='saveState saved';fillRecipeSelect();renderMetrics();renderRecipes()};$('#resetProfiles').onclick=()=>{if(!confirm('Ripristinare i range predefiniti?'))return;draftProfiles=normalizeProfiles(clone(DEFAULT_PROFILES));renderProfiles();markProfileDirty()};
function switchView(v){document.querySelectorAll('.nav,.view').forEach(x=>x.classList.remove('active'));document.querySelector(`.nav[data-view="${v}"]`).classList.add('active');$('#'+v).classList.add('active');let titles={balance:['Bilanciamento','Formula, controlla, scala e salva le tue ricette.'],ingredients:['Ingredienti','Il database tecnico delle tue materie prime.'],recipes:['Ricettario','Organizza e riapri le formule già collaudate.'],settings:['Profili & range','Personalizza i target tecnici per categoria.']};$('#pageTitle').textContent=titles[v][0];$('#pageSub').textContent=titles[v][1]}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$('#ingSearch').oninput=e=>renderIngredients(e.target.value);$('#recipeSearch').oninput=e=>{recipeQuery=e.target.value;renderRecipes()};
fillRecipeSelect();renderIngredients();renderRecipes();renderProfiles();newRecipe();
