const D=window.ICEC_DATA; const LS='icec_user_recipes_v1';
const profiles={
 cream:{label:'Gelato crema',ranges:{sugars:[18,22],fat:[7,16],msnf:[7,12],solids:[37,46],pac:[22,28],pod:[16,22]}},
 nuts:{label:'Gelato frutta secca',ranges:{sugars:[17,22],fat:[8,16],msnf:[5,11],solids:[38,48],pac:[22,29],pod:[15,22]}},
 choc:{label:'Gelato cioccolato',ranges:{sugars:[18,23],fat:[6,14],msnf:[5,11],solids:[38,48],pac:[22,29],pod:[16,23]}},
 fruit:{label:'Gelato frutta',ranges:{sugars:[22,24],fat:[0,10],msnf:[0,7],solids:[32,42],pac:[26,34],pod:[20,26]}},
 sorbet:{label:'Sorbetto',ranges:{sugars:[22,28],fat:[0,3],msnf:[0,2],solids:[30,40],pac:[27,35],pod:[21,28]}},
 granita:{label:'Granita',ranges:{sugars:[14,24],fat:[0,3],msnf:[0,2],solids:[14,30],pac:[18,32],pod:[14,25]}}
};
let state={items:[],advanced:false,profile:'cream',service:'display',temp:-13,notes:''};
const $=s=>document.querySelector(s); const fmt=(n,d=1)=>Number(n||0).toLocaleString('it-IT',{minimumFractionDigits:d,maximumFractionDigits:d});
function userRecipes(){try{return JSON.parse(localStorage.getItem(LS)||'[]')}catch{return[]}} function allRecipes(){return [...D.recipes,...userRecipes()]}
function calc(){let total=state.items.reduce((a,x)=>a+x.grams,0), m={kcal:0,carbs:0,sugars:0,fat:0,protein:0,fiber:0,salt:0,msnf:0,solids:0,water:0,pac:0,pod:0,cost:0}; state.items.forEach(x=>{let i=D.ingredients.find(z=>z.id===x.ingredientId); if(!i)return; Object.keys(m).forEach(k=>{if(k==='cost')m[k]+=x.grams*i[k]/1000; else m[k]+=x.grams*i[k]/100})}); if(total){['carbs','sugars','fat','protein','fiber','salt','msnf','solids','water','pac','pod'].forEach(k=>m[k]=m[k]/total*100);m.kcal=m.kcal/total*100} return {total,m}}
function serviceRange(key,base){if(key!=='pac')return base; if(state.service==='home')return [Math.max(base[0],27),Math.max(base[1],34)]; if(state.service==='custom'){let shift=Math.max(0,(-state.temp-13)*.9);return [base[0]+shift,base[1]+shift]} return base}
function status(v,r){if(v>=r[0]&&v<=r[1])return 'good'; let dist=v<r[0]?(r[0]-v)/(r[1]||1):(v-r[1])/(r[1]||1); return dist<.12?'warn':'bad'}
function renderFormula(){let {total}=calc(); $('#formula').innerHTML=state.items.map((x,n)=>`<div class="frow"><select onchange="setIng(${n},this.value)">${D.ingredients.map(i=>`<option value="${i.id}" ${i.id===x.ingredientId?'selected':''}>${i.name}</option>`).join('')}</select><input type="number" step="0.1" value="${x.grams}" onchange="setG(${n},this.value)"><div class="pct">${total?fmt(x.grams/total*100):0}%</div><button class="del" onclick="delRow(${n})">×</button></div>`).join(''); $('#totalG').textContent=fmt(total,1)+' g'; $('#totalTarget').value=Math.round(total); renderMetrics()}
window.setIng=(n,v)=>{state.items[n].ingredientId=v;renderFormula()}; window.setG=(n,v)=>{state.items[n].grams=Math.max(0,+v||0);renderFormula()}; window.delRow=n=>{state.items.splice(n,1);renderFormula()};
function renderMetrics(){let {total,m}=calc(), p=profiles[state.profile], keys=state.advanced?['sugars','fat','protein','msnf','solids','water','pac','pod','kcal','carbs','fiber','salt']:['sugars','fat','protein','solids','water','pac','pod','kcal']; let labels={sugars:'Zuccheri',fat:'Grassi',protein:'Proteine',msnf:'MSNF',solids:'Solidi totali',water:'Acqua',pac:'PAC',pod:'POD',kcal:'kcal / 100g',carbs:'Carboidrati',fiber:'Fibre',salt:'Sale'}; let scored=[]; $('#metrics').innerHTML=keys.map(k=>{let r=p.ranges[k]?serviceRange(k,p.ranges[k]):null, s=r?status(m[k],r):''; if(r)scored.push(s); let unit=['pac','pod'].includes(k)?'':(k==='kcal'?'':'%'); return `<div class="metric ${s}"><small>${labels[k]}</small><b>${fmt(m[k],k==='salt'?2:1)}${unit}</b>${r?`<em>target ${fmt(r[0],0)}–${fmt(r[1],0)}</em>`:''}</div>`}).join(''); let good=scored.filter(x=>x==='good').length, score=scored.length?Math.round(good/scored.length*100):0; $('#ring').textContent=score; $('#scoreText').textContent=score>=85?'Ben bilanciata':score>=60?'Da rifinire':'Da ribilanciare'; $('#scoreDetail').textContent=`${good}/${scored.length} parametri principali nel range del profilo ${p.label}.`; let adv=[]; for(const k of Object.keys(p.ranges)){let r=serviceRange(k,p.ranges[k]),v=m[k]; if(v<r[0])adv.push(`${labels[k]} basso (${fmt(v)}): target ${fmt(r[0],0)}–${fmt(r[1],0)}.`); if(v>r[1])adv.push(`${labels[k]} alto (${fmt(v)}): target ${fmt(r[0],0)}–${fmt(r[1],0)}.`)} if(state.service==='home')adv.unshift('Profilo freezer domestico: la valutazione PAC è più permissiva per compensare la temperatura più bassa. Verifica sempre la consistenza reale dopo 12–24 h.'); $('#advice').innerHTML=adv.length?adv.slice(0,5).map(x=>'• '+x).join('<br>'):'Tutti i parametri principali sono nel range. Registra comunque la prova sensoriale: temperatura, spatolabilità, dolcezza e fusione.'; $('#costTotal').textContent='€ '+fmt(m.cost,2); $('#costKg').textContent='€ '+fmt(total?m.cost/total*1000:0,2)}
function loadRecipe(id){let r=allRecipes().find(x=>x.id===id); if(!r)return; state.items=r.items.filter(x=>x.ingredientId).map(x=>({...x}));state.notes=r.notes||'';$('#notes').value=state.notes;renderFormula()}
function fillRecipeSelect(){let rs=allRecipes();$('#recipeLoad').innerHTML='<option value="">— Seleziona —</option>'+rs.map(r=>`<option value="${r.id}">${r.name}</option>`).join('');$('#dbcount').textContent=`${D.ingredients.length} ingredienti · ${rs.length} ricette`}
function renderIngredients(q=''){let keys=['name','kcal','carbs','sugars','fat','protein','fiber','salt','msnf','solids','water','pac','pod','cost'], lab=['Ingrediente','kcal','Carbo %','Zuccheri %','Grassi %','Proteine %','Fibre %','Sale %','MSNF %','Solidi %','Acqua %','PAC','POD','€/kg'];let rows=D.ingredients.filter(i=>i.name.toLowerCase().includes(q.toLowerCase()));$('#ingTable').innerHTML='<tr>'+lab.map(x=>`<th>${x}</th>`).join('')+'</tr>'+rows.map(i=>'<tr>'+keys.map((k,j)=>`<td>${j?fmt(i[k],k==='cost'?2:1):i[k]}</td>`).join('')+'</tr>').join('')}
function renderRecipes(){let {m:dummy}=calc();$('#recipeCards').innerHTML=allRecipes().map(r=>{let t=r.items.reduce((a,x)=>a+x.grams,0);return `<div class="rcard"><h3>${r.name}</h3><p>${r.items.length} ingredienti · ${fmt(t,0)} g</p><button onclick="openR('${r.id}')">Apri nel bilanciatore</button></div>`}).join('')}; window.openR=id=>{document.querySelector('[data-view=balance]').click();loadRecipe(id)};
function renderProfiles(){let labels={sugars:'Zuccheri %',fat:'Grassi %',msnf:'MSNF %',solids:'Solidi totali %',pac:'PAC',pod:'POD'};$('#profileEditor').innerHTML=Object.entries(profiles).map(([id,p])=>`<div class="profilebox"><h3>${p.label}</h3><div class="rangegrid"><b>Parametro</b><b>Min</b><b>Max</b>${Object.entries(p.ranges).filter(([k])=>labels[k]).map(([k,r])=>`<span>${labels[k]}</span><input value="${r[0]}" type="number" step=".1" onchange="profiles['${id}'].ranges['${k}'][0]=+this.value;renderMetrics()"><input value="${r[1]}" type="number" step=".1" onchange="profiles['${id}'].ranges['${k}'][1]=+this.value;renderMetrics()">`).join('')}</div></div>`).join('')}
$('#addRow').onclick=()=>{state.items.push({ingredientId:D.ingredients[0].id,grams:0});renderFormula()}; $('#recipeLoad').onchange=e=>loadRecipe(e.target.value); $('#profile').onchange=e=>{state.profile=e.target.value;renderMetrics()};$('#service').onchange=e=>{state.service=e.target.value;if(e.target.value==='home'){$('#temp').value=-18;state.temp=-18}else if(e.target.value==='display'){$('#temp').value=-13;state.temp=-13}renderMetrics()};$('#temp').onchange=e=>{state.temp=+e.target.value;$('#service').value='custom';state.service='custom';renderMetrics()};
function scaleTo(target){let {total}=calc();if(!total||target<=0)return;let f=target/total;state.items.forEach(x=>{let ing=D.ingredients.find(i=>i.id===x.ingredientId);let sensitive=ing&&(/neutro|stabil|diglicer|sale/i.test(ing.name));x.grams=Math.round(x.grams*f*(sensitive?10:1))/(sensitive?10:1)});renderFormula()}
$('#scaleBtn').onclick=()=>scaleTo(+$ ('#totalTarget').value);$('#plus10').onclick=()=>scaleTo(calc().total+10);$('#minus10').onclick=()=>scaleTo(Math.max(10,calc().total-10));$('#notes').oninput=e=>state.notes=e.target.value;
$('#saveRecipe').onclick=()=>{let name=prompt('Nome della nuova ricetta:');if(!name)return;let rs=userRecipes();rs.push({id:'u'+Date.now(),name,type:state.profile,items:state.items.map(x=>({...x})),notes:$('#notes').value,createdAt:new Date().toISOString()});localStorage.setItem(LS,JSON.stringify(rs));fillRecipeSelect();renderRecipes();alert('Ricetta salvata nel browser.')};
$('#baseMode').onclick=()=>{state.advanced=false;document.body.classList.remove('advanced');$('#baseMode').classList.add('active');$('#advMode').classList.remove('active');renderMetrics()};$('#advMode').onclick=()=>{state.advanced=true;document.body.classList.add('advanced');$('#advMode').classList.add('active');$('#baseMode').classList.remove('active');renderMetrics()};
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav,.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.view).classList.add('active');let titles={balance:['Bilanciamento','Formula, controlla, scala e salva le tue ricette.'],ingredients:['Ingredienti','Il database tecnico delle tue materie prime.'],recipes:['Ricettario','Riparti da una formula già collaudata.'],settings:['Profili & range','Adatta i target al prodotto e al tuo contesto.']};$('#pageTitle').textContent=titles[b.dataset.view][0];$('#pageSub').textContent=titles[b.dataset.view][1]});$('#ingSearch').oninput=e=>renderIngredients(e.target.value);
fillRecipeSelect();renderIngredients();renderRecipes();renderProfiles();loadRecipe(D.recipes[0].id);
